import {useMemo,useRef,useState} from 'react';
import {ArrowRight,Check,ChevronLeft,ChevronRight,Download,ExternalLink,ImagePlus,Lock,Menu,Monitor,Moon,RefreshCw,ShieldCheck,Sparkles,Tablet,Upload,Smartphone,X} from 'lucide-react';
import {categories,styles,sections,pages,features,plans,pagePrice,featurePrices,initialState} from './data';
import type {BuilderState,Device} from './types';
import {generateWebsite,websiteHtml} from './services/generator';
import {captureLead,whatsappUrl} from './services/leads';

const labels=['Category','Business','Style','Structure','Pages','Features','Assets','Your brief','Generate','Preview'];
const makeId=()=>crypto.randomUUID?.()||String(Date.now());

export default function App(){
 const [view,setView]=useState<'home'|'builder'|'pricing'>('home');
 const [step,setStep]=useState(1);
 const [s,setS]=useState<BuilderState>(initialState);
 const [progress,setProgress]=useState<string[]>([]);
 const [spec,setSpec]=useState<any>(null);
 const [device,setDevice]=useState<Device>('desktop');
 const [mobileNav,setMobileNav]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);
 const price=useMemo(()=>{const plan=plans.find(p=>p.name===s.plan)||plans[0];const included=plan.name==='Starter'?4:plan.name==='Professional'?7:plan.name==='Business'?10:15;return plan.price+Math.max(0,s.pages.length-included)*pagePrice+s.features.reduce((n,f)=>n+(featurePrices[f]||0),0);},[s]);
 const set=(k:keyof BuilderState,v:any)=>setS(x=>({...x,[k]:v}));
 const toggle=(k:'styles'|'sections'|'pages'|'features',v:string)=>setS(x=>({...x,[k]:x[k].includes(v)?x[k].filter(i=>i!==v):[...x[k],v]}));
 const next=()=>setStep(x=>Math.min(10,x+1)); const back=()=>setStep(x=>Math.max(1,x-1));
 const start=()=>{setView('builder');setStep(1);window.scrollTo({top:0,behavior:'smooth'});};
 const runGeneration=async()=>{setStep(10);setProgress([]);setSpec(null);try{const out=await generateWebsite(s,p=>setProgress(x=>[...x,p]));setSpec(out);setS(x=>({...x}));localStorage.setItem('nexaai-project',JSON.stringify({state:s,spec:out,status:'Awaiting Payment',price}));}catch{setProgress(['Generation failed — please retry.']);}};
 const upload=(files:FileList|null)=>{if(!files)return;const nextAssets=[...s.assets];Array.from(files).slice(0,8).forEach(f=>nextAssets.push({name:f.name,type:f.type,url:URL.createObjectURL(f)}));set('assets',nextAssets);};
 const exportSite=()=>{if(!spec)return;const blob=new Blob([websiteHtml(spec)],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(spec.business||'nexaai-site').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.html`;a.click();URL.revokeObjectURL(a.href);};
 if(view==='home')return <Home start={start} pricing={()=>setView('pricing')}/>;
 if(view==='pricing')return <Pricing s={s} setPlan={(p:string)=>{set('plan',p);setView('builder')}} back={()=>setView('builder')}/>;
 return <div className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setView('home')}><span className="brand-mark">N</span>NexaAI</button><div className="step-counter">Build / {String(step).padStart(2,'0')} <span>of 10</span></div><button className="price-pill" onClick={()=>setView('pricing')}>₹{price.toLocaleString('en-IN')} <span>View pricing</span></button><button className="icon-button mobile-only" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button></header>{mobileNav&&<div className="mobile-menu"><button onClick={()=>setView('pricing')}>Pricing</button><button onClick={()=>setView('home')}>Exit builder</button></div>}
 <main className="builder"><aside className="progress-rail"><div className="rail-title">Project builder</div>{labels.map((l,i)=><button className={step===i+1?'rail-step active':step>i+1?'rail-step done':'rail-step'} key={l} onClick={()=>step>i+1&&setStep(i+1)}><span>{step>i+1?<Check size={13}/>:i+1}</span>{l}</button>)}<div className="rail-card"><Sparkles size={18}/><strong>Quality over speed</strong><p>NexaAI plans, generates and validates your site before preview.</p></div></aside>
 <section className="builder-content">{step<9&&<StepHeader number={step} title={labels[step-1]} subtitle={step===1?'Tell us what kind of business you run.':step===2?'Give your brand the information it needs.':step===3?'Choose the visual direction.':step===4?'Shape the page into a conversion journey.':step===5?'Select the pages you need.':step===6?'Add useful functionality without surprise pricing.':'Bring your brand and references into the build.'}/>} {step===1&&<Category s={s} set={set} next={next}/>} {step===2&&<Business s={s} set={set} next={next}/>} {step===3&&<StyleStep s={s} set={set} toggle={toggle} next={next}/>} {step===4&&<Multi title="Sections" options={sections} selected={s.sections} toggle={v=>toggle('sections',v)} next={next}/>} {step===5&&<Multi title="Pages" options={pages} selected={s.pages} toggle={v=>toggle('pages',v)} next={next}/>} {step===6&&<Multi title="Features & add-ons" options={features} selected={s.features} toggle={v=>toggle('features',v)} priced next={next}/>} {step===7&&<Assets s={s} set={set} fileRef={fileRef} upload={upload} next={next}/>} {step===8&&<Brief s={s} set={set} next={next}/>} {step===9&&<Generate progress={progress} onGenerate={runGeneration}/>} {step===10&&<Preview spec={spec} progress={progress} device={device} setDevice={setDevice} onExport={exportSite} locked={true} retry={runGeneration}/>} {step<9&&<div className="nav-row"><button className="ghost" onClick={back} disabled={step===1}><ChevronLeft size={17}/> Back</button><span>Saved automatically in this session</span></div>}</section></main></div>}

function Home({start,pricing}:{start:()=>void;pricing:()=>void}){return <div className="marketing"><header className="marketing-nav"><button className="brand"><span className="brand-mark">N</span>NexaAI</button><nav><button onClick={pricing}>Pricing</button><button onClick={()=>document.getElementById('process')?.scrollIntoView({behavior:'smooth'})}>How it works</button></nav><button className="nav-cta" onClick={start}>Start building <ArrowRight size={16}/></button></header><section className="hero"><div className="hero-copy"><div className="kicker"><span className="pulse"/> AI website creation, without the agency wait</div><h1>Make your business<br/><em>look the part.</em></h1><p>Describe the website you want. Choose your direction. Add your assets. NexaAI turns it into a polished, conversion-ready experience.</p><div className="hero-actions"><button className="primary" onClick={start}>Start building <ArrowRight size={18}/></button><button className="text-button" onClick={pricing}>See transparent pricing</button></div><div className="trust"><ShieldCheck size={17}/> Preview before payment <span/> <ShieldCheck size={17}/> Starting at ₹4,999</div></div><div className="hero-preview"><div className="browser"><div className="browser-bar"><span/><span/><span/><small>nexaai / preview</small></div><div className="site-mock"><div className="mock-nav"><b>atelier.</b><i>Menu</i></div><div className="mock-hero"><small>Independent dining · Mumbai</small><h3>Food worth<br/><i>remembering.</i></h3><button>Reserve a table →</button></div><div className="mock-image"/><div className="mock-cards"><div/><div/><div/></div></div></div><div className="float-note"><Sparkles size={14}/> Crafted from your brief</div></div></section><section className="metrics"><div><b>10</b><span>guided build steps</span></div><div><b>₹4,999</b><span>starting price</span></div><div><b>100%</b><span>responsive output</span></div><div><b>3×</b><span>quality checkpoints</span></div></section><section id="process" className="process"><div className="section-label">The NexaAI method</div><h2>From a rough idea to<br/>a website people trust.</h2><div className="process-grid"><Card n="01" title="Configure" text="Business, brand, pages, features, references — you decide what matters."/><Card n="02" title="Generate" text="NexaAI creates a structured website specification before building the experience."/><Card n="03" title="Validate" text="The result is checked for responsive issues, missing content and broken interactions."/><Card n="04" title="Unlock" text="See the finished preview first. Pay only when you're ready to export."/></div></section><footer className="marketing-footer"><b>NexaAI</b><span>Premium websites, without the premium agency process.</span><button onClick={start}>Build yours →</button></footer></div>}
function Card({n,title,text}:{n:string;title:string;text:string}){return <article className="process-card"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>}
function StepHeader({number,title,subtitle}:{number:number;title:string;subtitle:string}){return <div className="step-head"><span>0{number}</span><div><h1>{title}</h1><p>{subtitle}</p></div></div>}
function Choice({active,onClick,children,sub}:{active:boolean;onClick:()=>void;children:any;sub?:string}){return <button className={active?'choice active':'choice'} onClick={onClick}><span className="choice-dot">{active&&<Check size={13}/>}</span><span><b>{children}</b>{sub&&<small>{sub}</small>}</span></button>}
function Category({s,set,next}:{s:BuilderState;set:any;next:()=>void}){return <div className="step-body"><div className="choice-grid">{categories.map(c=><Choice key={c} active={s.category===c} onClick={()=>set('category',c)}>{c}</Choice>)}</div><label className="field"><span>Describe my business</span><textarea value={s.customBusiness} onChange={e=>set('customBusiness',e.target.value)} placeholder="e.g. A neighbourhood bakery specialising in sourdough and seasonal pastries."/></label><button className="primary continue" onClick={next}>Continue <ArrowRight size={17}/></button></div>}
function Business({s,set,next}:{s:BuilderState;set:any;next:()=>void}){const fields:[keyof BuilderState,string,string][]=[['businessName','Business name','Atelier 27'],['tagline','Tagline','A short promise to your customers'],['location','Location','Mumbai, India'],['phone','Phone','+91…'],['whatsapp','WhatsApp','+91…'],['email','Email','hello@business.com'],['address','Address','Street, area, city'],['hours','Opening hours','Mon–Sat · 9am–7pm'],['socials','Social links','Instagram, LinkedIn, Facebook'],['existingWebsite','Existing website','Optional URL']];return <div className="step-body"><div className="field-grid">{fields.map(([k,l,p])=><label className="field" key={String(k)}><span>{l}</span><input value={String(s[k]||'')} onChange={e=>set(k,e.target.value)} placeholder={p}/></label>)}</div><label className="field full"><span>Business description</span><textarea value={s.description} onChange={e=>set('description',e.target.value)} placeholder="What do you sell? Why should someone choose you?"/></label><button className="primary continue" onClick={next}>Continue <ArrowRight size={17}/></button></div>}
function StyleStep({s,set,toggle,next}:{s:BuilderState;set:any;toggle:any;next:()=>void}){return <div className="step-body"><div className="choice-grid">{styles.map(v=><Choice key={v} active={s.styles.includes(v)} onClick={()=>toggle('styles',v)}>{v}</Choice>)}</div><div className="design-panel"><div><b>Let AI choose the best design</b><p>NexaAI will balance your business category, brief and references into a cohesive direction.</p></div><button className={s.theme==='ai'?'switch on':'switch'} onClick={()=>set('theme',s.theme==='ai'?'light':'ai')}><span/></button></div><div className="color-row"><label className="field"><span>Primary color</span><input type="color" value={s.primary} onChange={e=>set('primary',e.target.value)}/></label><label className="field"><span>Secondary color</span><input type="color" value={s.secondary} onChange={e=>set('secondary',e.target.value)}/></label><label className="field"><span>Font preference</span><select value={s.font} onChange={e=>set('font',e.target.value)}><option>Inter</option><option>Manrope</option><option>DM Sans</option><option>Playfair Display</option><option>Space Grotesk</option></select></label></div><button className="primary continue" onClick={next}>Continue <ArrowRight size={17}/></button></div>}
function Multi({title,options,selected,toggle,next,priced}:{title:string;options:string[];selected:string[];toggle:(v:string)=>void;next:()=>void;priced?:boolean}){return <div className="step-body"><div className="option-list">{options.map(v=><button key={v} className={selected.includes(v)?'option active':'option'} onClick={()=>toggle(v)}><span>{selected.includes(v)?<Check size={16}/>:null}</span><b>{v}</b>{priced&&featurePrices[v]>0&&<small>+ ₹{featurePrices[v].toLocaleString('en-IN')}</small>}</button>)}</div><button className="primary continue" onClick={next}>Continue <ArrowRight size={17}/></button></div>}
function Assets({s,set,fileRef,upload,next}:{s:BuilderState;set:any;fileRef:any;upload:(f:FileList|null)=>void;next:()=>void}){return <div className="step-body"><div className="upload-zone" onClick={()=>fileRef.current?.click()}><input ref={fileRef} hidden type="file" multiple accept="image/*" onChange={e=>upload(e.target.files)}/><div className="upload-icon"><Upload size={22}/></div><h3>Drop your brand assets here</h3><p>Logo, business photos, products, team images, screenshots or inspiration.</p><span>PNG, JPG, WEBP · up to 8 files</span></div>{s.assets.length>0&&<div className="asset-grid">{s.assets.map((a,i)=><div className="asset" key={a.name+i}><img src={a.url} alt={a.name}/><button onClick={()=>set('assets',s.assets.filter((_,x)=>x!==i))}><X size={13}/></button><small>{a.name}</small></div>)}</div>}<div className="reference-note"><ImagePlus size={19}/><div><b>References are part of the generation brief</b><p>Uploaded screenshots and inspiration are considered alongside your selections and written brief.</p></div></div><button className="primary continue" onClick={next}>Continue <ArrowRight size={17}/></button></div>}
function Brief({s,set,next}:{s:BuilderState;set:any;next:()=>void}){return <div className="step-body"><label className="field full"><span>Describe the website you want</span><textarea className="brief" value={s.brief} onChange={e=>set('brief',e.target.value)} placeholder="I want a luxury restaurant website with black and gold styling, large food photography, an online reservation CTA and WhatsApp contact."/></label><label className="field full"><span>Who is the website for?</span><input value={s.audience} onChange={e=>set('audience',e.target.value)} placeholder="e.g. Young professionals, families and destination diners"/></label><div className="brief-tips"><b>Good briefs mention</b><span>Audience</span><span>Desired feeling</span><span>Must-have actions</span><span>Competitors or references</span></div><button className="primary continue" onClick={next}>Review & generate <Sparkles size={17}/></button></div>}
function Generate({progress,onGenerate}:{progress:string[];onGenerate:()=>void}){const done=progress.length;return <div className="generation"><div className="generation-orb"><Sparkles size={34}/></div><h2>Ready to build something<br/><i>worth clicking.</i></h2><p>NexaAI will plan the site, generate the experience and run a quality pass before preview.</p><div className="stages">{['Analyzing your requirements','Planning website structure','Generating design','Adding content','Optimizing images','Running quality check','Finalizing website'].map((x,i)=><div className={done>i?'stage done':'stage'} key={x}><span>{done>i?<Check size={14}/>:i+1}</span>{x}{done>i&&<small>complete</small>}</div>)}</div><button className="primary generate" onClick={onGenerate}><Sparkles size={17}/> {done?'Regenerate website':'Generate my website'}</button><small className="quality-note">High-quality generation may take several minutes in production. This preview uses the configured generation pipeline.</small></div>}
function Preview({spec,progress,device,setDevice,onExport,locked,retry}:{spec:any;progress:string[];device:Device;setDevice:(d:Device)=>void;onExport:()=>void;locked:boolean;retry:()=>void}){return <div className="preview"><div className="preview-toolbar"><div><b>{spec?spec.business:'Your website'}</b><span className="status"><span/> {spec?'Preview ready':'Generating'}</span></div><div className="device-switch"><button className={device==='desktop'?'active':''} onClick={()=>setDevice('desktop')}><Monitor size={16}/></button><button className={device==='tablet'?'active':''} onClick={()=>setDevice('tablet')}><Tablet size={16}/></button><button className={device==='mobile'?'active':''} onClick={()=>setDevice('mobile')}><Smartphone size={16}/></button></div><div className="preview-actions"><button onClick={retry}><RefreshCw size={16}/> Regenerate</button><button className="locked" onClick={onExport}><Lock size={15}/> Export locked</button></div></div>{!spec?<div className="empty-preview"><Sparkles size={24}/><h3>Your preview is being prepared</h3><p>{progress.at(-1)||'Start generation to create the website.'}</p></div>:<div className={`frame ${device}`}><div className="generated-site" style={{'--primary':spec.colors.primary} as any}><div className="gen-nav"><b>{spec.business}</b><span>About &nbsp; Services &nbsp; Contact</span><button>Get started →</button></div><div className="gen-hero"><small>{spec.personality.join(' · ')}</small><h1>{spec.business}<br/><i>made memorable.</i></h1><p>{spec.content}</p><button> {spec.cta} <ArrowRight size={15}/></button></div><div className="gen-image"><div><span>Brand imagery</span><small>{spec.imageRequirements[0]}</small></div></div><div className="gen-sections">{spec.sections.slice(0,4).map((x:string)=><div key={x}><small>01</small><h2>{x}</h2><p>Thoughtful content, clear hierarchy and responsive composition.</p></div>)}</div><div className="gen-footer"><b>{spec.business}</b><span>Built with NexaAI</span></div></div></div>}<div className="lock-banner"><Lock size={17}/><div><b>Export is protected until payment is verified</b><p>You can preview the generated site before paying. Server-side Razorpay verification is required to unlock download and deployment.</p></div><button onClick={()=>location.hash='pricing'}>View price <ArrowRight size={15}/></button></div></div>}
function Pricing({s,setPlan,back}:{s:BuilderState;setPlan:(p:string)=>void;back:()=>void}){return <div className="pricing-page"><header className="marketing-nav"><button className="brand" onClick={back}><span className="brand-mark">N</span>NexaAI</button><button className="ghost" onClick={back}><ChevronLeft size={16}/> Back to builder</button></header><section className="pricing-head"><div className="section-label">Simple pricing</div><h1>Good websites shouldn't<br/><i>start at ₹20,000.</i></h1><p>Pick a starting point. Add only what you need. See the full calculation before payment.</p></section><div className="plans">{plans.map(p=><article className={s.plan===p.name?'plan selected':'plan'} key={p.name}><div className="plan-top"><span>{p.name}</span>{p.name==='Professional'&&<b>Most popular</b>}</div><strong>₹{p.price.toLocaleString('en-IN')}</strong><p>{p.description}</p><small>{p.includes}</small><button className={s.plan===p.name?'plan-button selected':'plan-button'} onClick={()=>setPlan(p.name)}>{s.plan===p.name?'Selected':'Choose plan'} <ArrowRight size={15}/></button></article>)}</div><div className="price-explainer"><div><b>Transparent by design</b><span>Base plan</span><span>+ extra pages · ₹{pagePrice.toLocaleString('en-IN')} each</span><span>+ selected features · shown in builder</span></div><strong>Preview first.<br/>Pay when ready.</strong></div></div>}
